// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Az3xNubVJpGkE9uzT8k_5ZT5OZdI6f0',
    appId: '1:781902418314:web:4643406acf805c511a3873',
    messagingSenderId: '781902418314',
    projectId: 'dummy-8a0cb',
    authDomain: 'dummy-8a0cb.firebaseapp.com',
    databaseURL: 'https://dummy-8a0cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dummy-8a0cb.appspot.com',
    measurementId: 'G-1EF7HMPKPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKsD5QWx6O71Ly8yOUUqrLFD4jXCqHKM',
    appId: '1:781902418314:android:e03d22a2e02c95781a3873',
    messagingSenderId: '781902418314',
    projectId: 'dummy-8a0cb',
    databaseURL: 'https://dummy-8a0cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dummy-8a0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx8bWc6OwCM9JS-SLsOk1kwQtElwv2HJA',
    appId: '1:781902418314:ios:62da12666cfac2151a3873',
    messagingSenderId: '781902418314',
    projectId: 'dummy-8a0cb',
    databaseURL: 'https://dummy-8a0cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dummy-8a0cb.appspot.com',
    iosBundleId: 'com.example.hostelClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx8bWc6OwCM9JS-SLsOk1kwQtElwv2HJA',
    appId: '1:781902418314:ios:5669d3e2cd7a88b71a3873',
    messagingSenderId: '781902418314',
    projectId: 'dummy-8a0cb',
    databaseURL: 'https://dummy-8a0cb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dummy-8a0cb.appspot.com',
    iosBundleId: 'com.example.hostelClient.RunnerTests',
  );
}
